version: 2
jobs:
  build_dev:
    working_directory: ~/project
    docker:
      - image: buildpack-deps:xenial
    environment:
      DEPLOY_ENVIRONMENT: dev
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export GIT_SHA="$(git rev-parse --short HEAD)"' >> $BASH_ENV
      # Better to create a docker image for this step
      - run:
          name: Install awscli, jq and npm
          command: |
            apt-get update
            apt-get install -y jq zip
            apt-get install -y software-properties-common
            add-apt-repository ppa:deadsnakes/ppa
            apt-get install python3.7
            python3.7 -m pip install awscli --upgrade
            aws configure set default.region $AWS_REGION
      - run:
          name: Deploy Functions
          command: |
            ./.circleci/deploy.sh
workflows:
  version: 2
  full:
    jobs:
      - build_dev:
          filters:
            branches:
              only: main