version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  setup_creds:
    - aws-cli/setup:
        aws-access-key-id: AWS_ACCESS_KEY
        aws-secret-access-key: AWS_ACCESS_SECRET
        aws-region: AWS_REGION_NAME
  build_dev:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.7.12
    environment:
      DEPLOY_ENVIRONMENT: dev
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export GIT_SHA="$(git rev-parse --short HEAD)"' >> $BASH_ENV
      # Better to create a docker image for this step
      - run:
          name: Install awscli, jq and npm
          command: |
            sudo apt-get update
            sudo apt-get install -y jq zip
            pip install awscli --upgrade
      - run:
          name: Deploy Functions
          command: |
            ./.circleci/deploy.sh
workflows:
  version: 2
  full:
    jobs:
      - build_dev:
          filters:
            branches:
              only: main